# Generated by Django 4.2.1 on 2023-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('usercontact', models.IntegerField(max_length=10)),
                ('userpass', models.CharField(max_length=100)),
                ('useradd', models.CharField(max_length=100)),
                ('usercity', models.CharField(max_length=100)),
                ('userstate', models.CharField(max_length=100)),
                ('userpin', models.IntegerField(max_length=6)),
            ],
        ),
    ]
