# Generated by Django 4.2.1 on 2023-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_delete_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usercontact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpin',
            field=models.CharField(max_length=6),
        ),
    ]
